# Generated by Django 2.2 on 2022-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisiontable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('officer', models.PositiveIntegerField(blank=True, null=True)),
                ('ensign', models.PositiveIntegerField(blank=True, null=True)),
                ('contract', models.PositiveIntegerField(blank=True, null=True)),
                ('soldier', models.PositiveIntegerField(blank=True, null=True)),
                ('cadet', models.PositiveIntegerField(blank=True, null=True)),
                ('listener', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('s_officer', models.PositiveIntegerField(blank=True, null=True)),
                ('s_ensign', models.PositiveIntegerField(blank=True, null=True)),
                ('s_contract', models.PositiveIntegerField(blank=True, null=True)),
                ('s_soldier', models.PositiveIntegerField(blank=True, null=True)),
                ('s_cadet', models.PositiveIntegerField(blank=True, null=True)),
                ('s_listener', models.PositiveIntegerField(blank=True, null=True)),
                ('s_total', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('whyout', models.CharField(blank=True, max_length=255, null=True)),
                ('datestart', models.DateField(blank=True, null=True)),
                ('dateend', models.DateField(blank=True, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=255, null=True)),
                ('numberoforder', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
