# Generated by Django 2.2 on 2022-06-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsz_system', '0002_outtable_military_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='outtable',
            name='daterealend',
            field=models.DateField(blank=True, null=True),
        ),
    ]
