# Generated by Django 2.2 on 2022-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsz_system', '0003_outtable_daterealend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outtableqqq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.CharField(blank=True, max_length=255, null=True)),
                ('military_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=255, null=True)),
                ('whyout', models.CharField(blank=True, max_length=255, null=True)),
                ('numberoforder', models.CharField(blank=True, max_length=255, null=True)),
                ('datestart', models.DateField(blank=True, null=True)),
                ('dateend', models.DateField(blank=True, null=True)),
                ('daterealend', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
