# Generated by Django 2.2 on 2022-06-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsz_system', '0003_outtable_daterealend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outtable',
            old_name='name',
            new_name='surname',
        ),
    ]
