# Generated by Django 2.2 on 2022-07-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsz_system', '0004_auto_20220630_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outtable',
            old_name='surname',
            new_name='name',
        ),
    ]
